### ISSUE TITLE
running a spring fat jar with aspectj

### ISSUE THREAD

**Issue by stevensouza** [scratches/spring-boot-ltw#3]
Thanks for the work.  A question for you...

Should you be able to run a Spring fat jar  using the following command?

`$ java -javaagent:$HOME/.m2/repository/org/aspectj/aspectjweaver/1.8.13/aspectjweaver-1.8.13.jar -jar target/*.jar`

I have tried that approach using an ajc-aop.xml file, similar to the following and it doesn't seem to be working

`java -jar libs/my_spring_app.jar  -javaagent:libs/aspectjweaver.jarDorg.aspectj.weaver.loadtime.configuration=file:config/ajc-aop.xml  `

Thanks in advance.

**Comment by dsyer** [comment]
That second command looks like a copy-paste error? You need the agent and the system properties on the command line before `-jar` I think as well.
