### ISSUE TITLE
Update Java 11 OpenJDK, Spring Boot 2.2.4 and Add Travis for CI

### ISSUE THREAD

**Issue by lofidewanto** [scratches/spring-boot-ltw#5]
Hi all,

My repo: https://github.com/lofidewanto/spring-boot-aspectj

I've done following things in this repo:
- Update to Java 11 and Spring Boot 2.2.4
- Add Travis for CI. Therefore I added Logger instead of System.out to control the output. Travis does not like to have a lot of text in its console.
- Rename some projects / directories to comply Maven and make them clearer. ArtifactId, directories and so on (see my screenshot) 

<img width="422" alt="Bildschirmfoto 2020-04-20 um 11 15 42" src="https://user-images.githubusercontent.com/1212950/79735273-4dfabe00-82f8-11ea-8598-f68a87b58190.png">

- Add more docs..

@dsyer If you like I could make a PR. Thanks a lot for this nice work explaining AspectJ!

**Comment by dsyer** [comment]
Not sure I understand the screenshot. Can you break the directory names out into a separate PR?

**Comment by lofidewanto** [comment]
Actually it is just a rename of the directory so you don't see like this one. Original source: 

<img width="422" alt="Bildschirmfoto 2020-04-20 um 12 51 31" src="https://user-images.githubusercontent.com/1212950/79743889-b3a17700-8305-11ea-88fc-fe6508218767.png">

As you can see:
- multi-ltw and multi-ctw have the same under modules "app" and "aspects". That's for me irritating see on the top "app" and "aspects" - this makes difficult to see as ctw-app and ctw-aspects.
- In the refactored structure above it is easier to see the deps: multi-ctw/ctw-app and multi-ctw/ctw-aspects and also analog to multi-ltw.
- Best practices in Maven is actually using same name for directories and artifactIds.

Sorry, forget to answer your question: it would be difficult for me to separates those PR's in a smaller chunks, yes this is my fault, actually I need to make those smaller PRs, but I did it in the "night" so it was in the "flow" 😀Sorry for this.

Thanks,
Lofi

**Comment by dsyer** [comment]
OK, I can live with that. I quite often don't care for artifact ids as directory names, but I don't see the harm in this case.

**Comment by lofidewanto** [comment]
OK, I created a PR.

Thanks,
Lofi
